apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: criticapp-web
  namespace: criticapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __APP_DOMAIN__
      secretName: criticapp-web-tls
  rules:
    - host: __APP_DOMAIN__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: criticapp-web
                port:
                  number: 80