apiVersion: batch/v1
kind: Job
metadata:
  name: criticapp-migrate
  namespace: criticapp
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: criticapp-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/batman-nair/criticapp:latest
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: criticapp-config
            - secretRef:
                name: criticapp-secrets
