apiVersion: v1
kind: Secret
metadata:
  name: criticapp-secrets
  namespace: criticapp
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
  DB_NAME: "criticdb"
  DB_USER: "criticuser"
  DB_PASSWORD: "replace-me"
  DB_HOST: "criticapp-db"
  DB_PORT: "5432"
  OMDB_API_KEY: "replace-me"
  RAWG_API_KEY: "replace-me"
