apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: criticapp-web
  namespace: criticapp
  labels:
    app: criticapp-web
spec:
  selector:
    matchLabels:
      app: criticapp-web
  namespaceSelector:
    matchNames:
      - criticapp
  endpoints:
    - port: http
      path: /metrics/
      interval: 30s
      scrapeTimeout: 10s
