apiVersion: v1
kind: Service
metadata:
  name: criticapp-web
  namespace: criticapp
spec:
  selector:
    app: criticapp-web
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
