apiVersion: v1
kind: Service
metadata:
  name: criticapp-web
  namespace: criticapp
  labels:
    app: criticapp-web
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/"
    prometheus.io/port: "80"
spec:
  selector:
    app: criticapp-web
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
